# Configuration for cargo-deny
# See: https://embarkstudios.github.io/cargo-deny/

[graph]
targets = []

[licenses]
unlicensed = "deny"
# List of explicitly allowed licenses
# cargo-deny uses SPDX license identifiers
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Unlicense",
    "0BSD",
    "Zlib",
    "BSL-1.0",
]

# List of crates that are allowed to have specific licenses
exceptions = [
    # Allow dual-licensed crates
    { allow = ["MIT", "Apache-2.0"], name = "addr2line" },
    { allow = ["MIT", "Apache-2.0"], name = "autocfg" },
    { allow = ["MIT", "Apache-2.0"], name = "bitflags" },
    { allow = ["MIT", "Apache-2.0"], name = "bytes" },
    { allow = ["MIT", "Apache-2.0"], name = "cfg-if" },
    { allow = ["MIT", "Apache-2.0"], name = "futures" },
    { allow = ["MIT", "Apache-2.0"], name = "libc" },
    { allow = ["MIT", "Apache-2.0"], name = "serde" },
    { allow = ["MIT", "Apache-2.0"], name = "serde_json" },
    { allow = ["MIT", "Apache-2.0"], name = "tokio" },
    { allow = ["MIT", "Apache-2.0"], name = "tower-lsp" },
    { allow = ["MIT", "Apache-2.0"], name = "url" },
    { allow = ["Unlicense", "MIT"], name = "aho-corasick" },
    { allow = ["MIT", "Zlib", "Apache-2.0"], name = "miniz_oxide" },
    { allow = ["Apache-2.0", "BSL-1.0"], name = "ryu" },
    { allow = ["MIT", "Apache-2.0", "Unicode-3.0"], name = "unicode-ident" },
]

copyleft = "warn"

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "allow"
yanked = "deny"
notice = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
