name: Rust

on:
  push:
    branches: [ "release-0.0.2" ]
  pull_request:
    branches: [ "release-0.0.2" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose

